{{HTML::script('assets/plugins/jquery-1.11.js')}}
{{HTML::script('assets/plugins/jquery-migrate-1.2.1.js')}}
{{HTML::script('assets/plugins/jquery-ui/jquery-ui-1.10.4.min.js')}}
{{HTML::script('assets/plugins/bootstrap/bootstrap.min.js')}}
{{HTML::script('assets/plugins/bootstrap-dropdown/bootstrap-hover-dropdown.min.js')}}
{{HTML::script('assets/plugins/bootstrap-select/bootstrap-select.js')}}
{{HTML::script('assets/plugins/icheck/icheck.js')}}
{{HTML::script('assets/plugins/mcustom-scrollbar/jquery.mCustomScrollbar.concat.min.js')}}
{{HTML::script('assets/plugins/nprogress/nprogress.js')}}
{{HTML::script('assets/plugins/breakpoints/breakpoints.js')}}
{{HTML::script('assets/plugins/numerator/jquery-numerator.js')}}

{{HTML::script('assets/plugins/metrojs/metrojs.min.js')}}
{{HTML::script('assets/plugins/fullcalendar/moment.min.js')}}
{{HTML::script('assets/plugins/fullcalendar/fullcalendar.min.js')}}
{{HTML::script('assets/plugins/simple-weather/jquery.simpleWeather.min.js')}}
{{HTML::script('assets/plugins/google-maps/markerclusterer.js')}}
{{HTML::script('assets/plugins/google-maps/gmaps.js')}}
{{HTML::script('assets/plugins/charts-flot/jquery.flot.js')}}
{{HTML::script('assets/plugins/charts-flot/jquery.flot.animator.min.js')}}
{{HTML::script('assets/plugins/charts-flot/jquery.flot.resize.js')}}
{{HTML::script('assets/plugins/charts-flot/jquery.flot.time.min.js')}}
{{HTML::script('assets/plugins/charts-morris/raphael.min.js')}}
{{HTML::script('assets/plugins/charts-morris/morris.min.js')}}
{{HTML::script('assets/plugins/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js')}}
{{HTML::script('assets/js/calendar.js')}}
{{HTML::script('assets/js/dashboard.js')}}
{{HTML::script('assets/js/application.js')}}
    <!-- END MANDATORY SCRIPTS -->
